name: DevSecOps Report Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  devsecops-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ensure reports directory exists
        run: |
          mkdir -p reports

      - name: Run Bandit (SAST)
        run: |
          python -m bandit -r sample_code -f json -o reports/bandit_report.json --exit-zero


      - name: Run Flake8 (Lint)
        run: |
          python -m flake8 sample_code --output-file reports/flake8_report.txt --exit-zero

      - name: Run Universal DevSecOps Reporter
        run: |
          python -m universal_reporter.main

      - name: Upload HTML Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: devsecops-report
          path: devsecops_report.html
